# Also see https://github.com/beryx-gist/badass-runtime-example-javafx/blob/master/.github/workflows/gradle.yml
name: 🏗️ qr-code-app standalone

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4.1.1
      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Execute qr-code-app:runtime
        run: ./gradlew --info --stacktrace qr-code-app:runtime
      - name: Set distribution os env var
        run: |
          OS_NAME=$(echo "${{ matrix.os }}" | cut -d'-' -f1)
          echo "OS=${OS_NAME}" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: qr-code-app-${{ OS }}
          path: qr-code-app/build/qr-code-with-logo-app/
