# Also see https://github.com/beryx-gist/badass-runtime-example-javafx/blob/master/.github/workflows/gradle.yml
name: Build platform-specific qr-code-app images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4.1.1
      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Execute qr-code-app:jpackageImageZip
        run: ./gradlew --info --stacktrace qr-code-app:jpackageImageZip
      - uses: actions/upload-artifact@v3
        with:
          name: qr-code-app-${{ matrix.os }}
          path: qr-code-app/build/dist/qr-code-app.zip

